name       : playmyvideos
version    : 0.2.5
release    : 1
source     :
    - https://github.com/artemanufrij/playmyvideos/archive/0.2.5.tar.gz : 5e583912149e74456cf28595e87d1e6f7191f2b01491c7380738b16ff55a5907
license    : GPL-2.0
component  : multimedia.vlc
summary    : A video player for watching local video files
description: |
    A video player for watching local video files
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %apply_patches
    mkdir cmake
    install -m 00644 $pkgfiles/cmake/*.cmake cmake/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
