name       : playmyvideos
version    : 0.3.2
release    : 2
source     :
    - https://github.com/artemanufrij/playmyvideos/archive/0.3.2.tar.gz : 5acf2f446772aa3bba6e8d648826a6e3722efeaea4104024056774e2ef884a9a
license    : GPL-2.0
component  : multimedia.vlc
summary    : A video player for watching local video files
description: |
    A video player for watching local video files
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %apply_patches
    mkdir cmake
    install -m 00644 $pkgfiles/cmake/*.cmake cmake/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
